# GNUmakefile

PACKAGE_DIR=../..
PACKAGE=SwiftyEchoDaemon
debug=on

SwiftyEchoDaemon_SWIFT_MODULES = SwiftSockets

include $(PACKAGE_DIR)/config.make

all : all-tool

include $(PACKAGE_DIR)/rules.make
