# GNUmakefile

PACKAGE_DIR=../..
PACKAGE=$(notdir $(shell pwd))
$(PACKAGE)_TYPE = tool

SwiftyEchoDaemon_SWIFT_MODULES = SwiftSockets

include $(PACKAGE_DIR)/config.make
include $(PACKAGE_DIR)/rules.make
